version: '3'
services:
  app:
    container_name: knowledgebasedemo
    image: dhairya25/knowledgebasedemo
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - dbpostgresql
    links:
      - dbpostgresql
  dbpostgresql:
    image: postgres:9.6.8-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3